version: "2"
services:
  mysql:
    image: mariadb:10.10
    hostname: mysql
    container_name: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: slurm_acct_db
      MYSQL_USER: slurm
      MYSQL_PASSWORD: slurm2023!!
    expose:
      - "3306"
  slurmctld:
    image: inojeon/slurm_master_rocky8:21
    hostname: slurmctld
    container_name: slurmctld
    volumes:
      - ./EDISON2/home:/home
      - ./EDISON2/singularity:/singularity
      - ./EDISON2/solvers:/solvers
      - /Users/ino/Work/kisti/edison/2023/slurm-api:/slurm-api
    ports:
      - "6817:6817"
      - "6818:6818"
      - "6819:6819"
      - "8000:8000"
    depends_on:
      - mysql
  slurmd-0:
    image: inojeon/slurm_worker_rocky8:21
    hostname: slurmd-0
    container_name: slurmd-0
    volumes:
      - ./EDISON2/home:/home
      - ./EDISON2/singularity:/singularity
      - ./EDISON2/solvers:/solvers
    expose:
      - "6818"
    depends_on:
      - "slurmctld"
  slurmd-1:
    image: slurm_worker_rocky8:21
    hostname: slurmd-1
    container_name: slurmd-1
    volumes:
      - ./EDISON2/home:/home
      - ./EDISON2/singularity:/singularity
      - ./EDISON2/solvers:/solvers
    expose:
      - "6818"
    depends_on:
      - "slurmctld"
volumes:
  slurm_jobdir:
