apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: edison2-pvc
  namespace: slurm
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteMany
  # storageClassname:
